### ISSUE TITLE
octokit.repos.getCommunityProfileMetrics() fails with 404 on private repositories

### ISSUE THREAD

**Issue by gabbloquet** [octokit/octokit.js#1775]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] Node.js app

**Versions**

v18.00 now and i think that my problem come from it.

**What happened?**

I try to use the new function :

```js
    result = await OCTOKIT.repos.getCommunityProfileMetrics({
      owner: ORGANIZATION_NAME,
      repo: REPO_NAME,
    });
```

and i received a 415. I tried to add :

```js
      headers: {
        Accept: 'application/vnd.github.v3.raw',
      },
```

and

```js
      headers: {
        Accept: 'application/json',
      },
```

but it didn't works, do you have an idea ? :)

**Minimal test case to reproduce the problem**

Just add this kind of method on your project : 

```js
    result = await OCTOKIT.repos.getCommunityProfileMetrics({
      owner: ORGANIZATION_NAME,
      repo: REPO_NAME,
    });
```

**What did you expect to happen?**

That it returns all informations, like on documentation : an overall health score, repository description, the presence of documentation, detected code of conduct, detected license, and the presence of ISSUETEMPLATE, PULLREQUEST_TEMPLATE, README, and CONTRIBUTING files.

**What the problem might be**

MediaType maybe ?
Moreover i have a problem now with intellij : 
![image](https://user-images.githubusercontent.com/25029077/85577176-4f6a9e80-b639-11ea-9437-4e4ecf76cdce.png)

**Comment by gr2m** [comment]
Can you try this?

```js
   result = await OCTOKIT.repos.getCommunityProfileMetrics({
      mediaType: { previews: ['black-panther'] },
      owner: ORGANIZATION_NAME,
      repo: REPO_NAME,
    });
```

**Comment by gabbloquet** [comment]
Mmmhhh interesting, it works with :
```
owner: "octokit",
  repo: "rest.js",
```
But not with my organisation and repo config, while others requests works 🤔 
OCTOKIT.repos.getContents, OCTOKIT.repos.listBranches or OCTOKIT.repos.getReadme work for exemple !
Do you have an idea ?

**Comment by gr2m** [comment]
What errors do you get? If your repo is private, then it’s likely a problem with authentication

**Comment by gabbloquet** [comment]
```
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 24 Jun 2020 18:39:42 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; param=jean-grey-preview.symmetra-preview; format=json, github.black-panther-preview; format=json',
    'x-github-request-id': 'C719:35EA:1590EC2:199797D:5EF39DEE',
    'x-oauth-scopes': 'admin:org, repo',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4988',
    'x-ratelimit-reset': '1593027271',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/dktunited/mybusiness/community/profile',
    headers: {
      accept: 'application/vnd.github.jean-grey-preview+json,application/vnd.github.symmetra-preview+json,application/vnd.github.black-panther-preview+json',
      'user-agent': 'check octokit-rest.js/18.0.0 octokit-core.js/3.1.0 Node.js/14.2.0 (macOS Catalina; x64)',
      'time-zone': 'Europe/Paris',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://developer.github.com/v3/repos/community/#retrieve-community-profile-metrics'
}

```

If it was the case my others tests would have miss no ?

**Comment by gr2m** [comment]
Yes that looks like an authentication problem. The other tests probably worked because they were for public repositories

**Comment by gabbloquet** [comment]
All the tests are for the same repo :/
Actually the project objective is too check for a repo if it has a good configuration.
And for my others calls it works, only for this it fails :/

**Comment by gr2m** [comment]
Hm this might be a GitHub API bug. I was able to reproduce the problem using curl an a private repository of mine

```
curl -v -H"Authorization: token [TOKEN]" -H"Accept: application/vnd.github.black-panther-preview+json" https://api.github.com/repos/gr2m/sandbox-private/community/profile
```

Failed with a 404, while getting the repository works just fine

```
curl -v -H"Authorization: token [TOKEN]" https://api.github.com/repos/gr2m/sandbox-private
```

Can you please contact support at https://support.github.com/contact, and reference this issue? The curl commands above will help them reproduce the problem independent of Octokit

**Comment by gabbloquet** [comment]
Done thanks a lot ! :)

**Comment by gabbloquet** [comment]
Hey @gr2m, i hope you're fine :) 
Here the Github's support response : 

_Our engineering teams got back to me and informed me that at this current time, this is expected behavior and the endpoint will only work for public repositories. I have also pinged our documentations team to get our endpoint documentation updated to reflect this, but I am unable to provide an ETA for that. As this endpoint is in preview, it may be updated in the future to allow for private repositories as well but again I do not know if or when that would happen._

For the moment /community/profile is not available for private repo :/
Hope it will be soon because thanks to me it's an interesting feature.

**_Thanks for your time and help, have a really nice day :)_**

**Comment by gabbloquet** [comment]
For people who meet this kind of problem you can for the moment do something like that, to check if the repo contains contributing file : 

```
const CONTRIBUTING_FILE = 'CONTRIBUTING.md';
const result = await OCTOKIT.repos.getContents({
      owner: ORGANIZATION,
      repo: repo.name,
      path: CONTRIBUTING_FILE,
    });
```

**Comment by gr2m** [comment]
Thank your for keeping us in the loop 👍

**Comment by gr2m** [comment]
I'm fairly sure that 

> _Our engineering teams got back to me and informed me that at this current time, this is expected behavior and the endpoint will only work for public repositories. I have also pinged our documentations team to get our endpoint documentation updated to reflect this, but I am unable to provide an ETA for that. As this endpoint is in preview, it may be updated in the future to allow for private repositories as well but again I do not know if or when that would happen._
> 
> For the moment /community/profile is not available for private repo :/
> Hope it will be soon because thanks to me it's an interesting feature.

Did you hear any news? The `black-panther` preview was graduated, but the community profile endpoint does still not work for private repositories.

There is nothing actionable for @octokit so I'm going to close the issue, but please keep us posted if you hear anything else
